In [1]:
import pandas as pd

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
from sklearn.neighbors import KNeighborsClassifier

In [5]:
from sklearn.metrics import confusion_matrix

In [6]:
from sklearn.metrics import classification_report

In [7]:
df=pd.read_csv("500hits.csv",encoding="latin-1")

In [8]:
df.head(10)

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1
5,Carl Yastrzemski,23,3308,11988,1816,3419,646,59,452,1844,1845,1393,168,116,0.285,1
6,Paul Molitor,21,2683,10835,1782,3319,605,114,234,1307,1094,1244,504,131,0.306,1
7,Eddie Collins,25,2826,9949,1821,3315,438,187,47,520,1499,286,744,173,0.333,1
8,Willie Mays,22,2992,10881,2062,3283,523,140,660,1903,1464,1526,338,103,0.302,1
9,Eddie Murray,21,3026,11336,1627,3255,560,35,504,1917,1333,1516,110,43,0.287,1

In [9]:
df=df.drop(columns=["PLAYER","CS"])

In [10]:
df

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA,HOF
0,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,0.366,1
1,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,0.331,1
2,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,0.345,1
3,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,0.310,1
4,21,2792,10430,1736,3430,640,252,101,0,963,327,722,0.329,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,15,1920,6653,1105,1665,285,39,291,964,1224,1427,225,0.250,0
461,17,1829,6092,900,1664,379,10,275,1065,936,1453,20,0.273,0
462,15,1834,6499,1062,1661,338,67,210,761,960,1190,315,0.256,0
463,16,1822,6309,714,1660,254,25,54,593,396,489,74,0.263,0
464,15,1468,5629,785,1660,247,71,61,499,266,471,267,0.295,0

In [11]:
X=df.iloc[:,0:13]

In [12]:
y=df.iloc[:,13]

In [13]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=11,test_size=0.2)

In [37]:
scaler=MinMaxScaler(feature_range=(0,1)).set_output(transform="pandas")

In [38]:
X_train=scaler.fit_transform(X_train)

In [39]:
X_test=scaler.fit_transform(X_test)

In [40]:
X_train

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA
289,0.466667,0.352554,0.313829,0.135036,0.131673,0.173984,0.120915,0.423592,0.506313,0.195284,0.678202,0.009292,0.225000
288,0.133333,0.255438,0.249898,0.124696,0.132859,0.349593,0.372549,0.045576,0.175011,0.140441,0.185950,0.171551,0.383333
350,0.200000,0.236722,0.188541,0.136861,0.076710,0.170732,0.199346,0.053619,0.274271,0.310097,0.323864,0.021444,0.375000
196,0.400000,0.418311,0.396858,0.246959,0.243575,0.385366,0.290850,0.113941,0.367436,0.231164,0.404959,0.170836,0.350000
184,0.533333,0.535660,0.486117,0.447080,0.280348,0.395122,0.202614,0.315013,0.471920,0.491030,0.567665,0.097212,0.250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,0.400000,0.293880,0.244616,0.167275,0.088573,0.255285,0.215686,0.207775,0.358729,0.117376,0.653926,0.218013,0.266667
91,0.933333,0.532119,0.492618,0.246959,0.256623,0.347967,0.457516,0.033512,0.000000,0.274218,0.040806,0.138670,0.183333
80,0.466667,0.321700,0.322633,0.272506,0.283116,0.263415,0.584967,0.079088,0.292120,0.125577,0.134298,0.186562,0.641667
191,0.533333,0.585230,0.506840,0.208029,0.263345,0.344715,0.147059,0.123324,0.413583,0.254741,0.612603,0.224446,0.175000
409,0.200000,0.210420,0.164025,0.153285,0.035192,0.219512,0.049020,0.380697,0.472791,0.307022,0.412190,0.021444,0.300000

In [ ]:
scaler=MinMaxScaler(feature_range=(0,1))

In [30]:
X_train=scaler.fit_transform(X_train)

In [32]:
X_test=scaler.transform(X_test)

In [41]:
knn=KNeighborsClassifier(n_neighbors=8)
#The n_neighbors parameter in a k-Nearest Neighbors (KNN) classifier determines the number of nearest data points (neighbors) the algorithm considers when making a prediction for a new sample.
#Small n_neighbors (e.g., 1):
#High model complexity, fits training data tightly.
#Large n_neighbors (e.g., 50):
#Low model complexity, smoother decision boundaries.

In [19]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=8)

In [20]:
y_pred=knn.predict(X_test)

In [21]:
print(y_pred)

[0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0 1 1 1 0 1 0
 0 1 0 0 1 0 0 0 1 0 0 1 0 1 1 0 1 1 1 0 0 1 0 1 0 1 1 0 0 1 1 0 1 0 0 0 0
 1 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 1 1]

In [42]:
y_test

144    1
296    0
39     1
247    0
197    0
      ..
259    0
451    0
380    0
74     1
31     1
Name: HOF, Length: 93, dtype: int64

In [22]:
knn.score(X_test,y_test)#it will check how accurate is ur test data is.

0.8279569892473119

In [23]:
cm=confusion_matrix(y_test,y_pred)

In [24]:
print(cm)

[[55 12]
 [ 4 22]]

In [25]:
##[[true positive,false positive]
##[false negative,true negative]]

In [26]:
cr=classification_report(y_test,y_pred)

In [27]:
print(cr)

              precision    recall  f1-score   support

           0       0.93      0.82      0.87        67
           1       0.65      0.85      0.73        26

    accuracy                           0.83        93
   macro avg       0.79      0.83      0.80        93
weighted avg       0.85      0.83      0.83        93

In [28]:
print(knn.n_samples_fit_)

372

In [29]:
# 55/(55+4)=0.93
# 55/(55+12)=0.82
# 2*0.93*0.82/(0.93+0.82)=0.87
# (0.93+0.65)/2=0.79
# 22/(12+22)=0.65
# 22/(22+4)=0.85
# 2*0.65*0.85/(0.65+0.85)=0.73
# (0.82+0.85)/2=0.83
# (0.87+0.73)/2=0.80